<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>QtDataSync::AccountManager</name>
    <message>
        <location filename="../datasync/accountmanager.cpp" line="+159"/>
        <source>Password must not be empty.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+23"/>
        <location line="+22"/>
        <source>Already importing. Only one import at a time is possible.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::AccountManagerPrivate</name>
    <message>
        <location filename="../datasync/accountmanager_p.cpp" line="+119"/>
        <location line="+26"/>
        <source>Failed to generate export data. You must be registered to a server to export data.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-19"/>
        <location line="+37"/>
        <source>Password must not be empty.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-7"/>
        <source>Failed import data. Data invalid.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Failed to decrypt data. Data invalid or password wrong.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::ChangeController</name>
    <message>
        <location filename="../datasync/changecontroller.cpp" line="+75"/>
        <location line="+25"/>
        <location line="+105"/>
        <source>Failed to upload changes to server.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::ExchangeBuffer</name>
    <message>
        <location filename="../datasync/rothreadedbackend/exchangebuffer.cpp" line="+28"/>
        <source>ExchangeBuffer already open</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Failed to send data to partner device</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::ExchangeEngine</name>
    <message>
        <location filename="../datasync/setup.cpp" line="+450"/>
        <source>Password for trusted import must not be empty</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+175"/>
        <source>Import data must be a JSON object</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::RemoteConnector</name>
    <message>
        <location filename="../datasync/remoteconnector.cpp" line="+791"/>
        <source>Failed to load user identity! Make shure your keystore is available.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+109"/>
        <source>Server is not compatibel with your application version.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Authentication failed. Try to remove and add your device again, or reset your account!</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Account access (import) failed. The partner device was not available or did not accept your request!</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Cannot update key! This client is not using the latest existing keys.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Cannot update key! At least one client did not receive the previous key update.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Internal application error. Check the logs for details.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Data quota hit. You need to synchronize changes to other devices before you can upload more changes.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Unknown error occured.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::SyncController</name>
    <message>
        <location filename="../datasync/synccontroller.cpp" line="+164"/>
        <source>Data downloaded from server is invalid.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::UserExchangeManager</name>
    <message>
        <location filename="../datasync/userexchangemanager.cpp" line="+146"/>
        <location line="+28"/>
        <source>Cannot export data if UserExchangeManager is not in active state</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+9"/>
        <source>No import data received from passed user.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+81"/>
        <source>&lt;Unnamed&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Invalid data received from %1:%2.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
